spring:
  application:
    name: shopjoy-ecommerce-system
  
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
      introspection:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
    http:
      path: /graphql
